#!/bin/sh -e

n=0
while [ "$n" -lt 16 ]; do
    col=$n

    [ "$n" -gt 7 ] && col="8;5;$n"
    printf '\033[4%sm%*s\033[m' "$col" "4" ""

    n=$((n+1))
    [ "$((n % 8))" -eq 0 ] && printf '\n'
done
unset n col
