#!/usr/bin/env bash

trap "printf '[?25h[?7h\n'" EXIT INT

printf '[?25l[?7l[2J[H'

for i in {0..4}; do
        for j in {1..7}; do
                printf "\e[38;5;%sm ██████ " "$j"
        done
        printf "\n\e[m"
done

read -r _
