#!/usr/bin/env bash
#
# randwal - Random Wallpaper
#############################

dir="/home/sidd_dino/Pictures/wallpaper"

for item in "$dir"/*; do
    images+=("$item")
done

dir="/home/sidd_dino/Pictures/wallpaper_bin"

for item in "$dir"/*; do
    images+=("$item")
done

(( img_num = RANDOM % ${#images[@]} ))

feh --bg-fill "${images[$img_num]}"


