#!/bin/sh

BAT_dir="/sys/class/power_supply/BAT0"

d="$(date '+%a %d %b')"
t="$(date '+%H:%M')"

read -r b_cap < "$BAT_dir/capacity"
read -rn1 b_stat < "$BAT_dir/status"

notify-send -u critical "[D] $d
[T] $t
[B] $b_cap $b_stat"
