#!/usr/bin/bash

BAT_dir="/sys/class/power_supply/BAT0"

d="$(date '+%a %d %b')"
t="$(date '+%H:%M')"

b_cap="$( < "$BAT_dir/capacity")"
b_stat="$( < "$BAT_dir/status")"

notify-send -u critical "[D] $d
[T] $t
[B] $b_cap ${b_stat::1}"
